package com.nutrilab.app;

import android.app.*;
import android.os.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.Executors;
import org.json.*;

public class MainActivity extends Activity {
    // NutriLab visual system: warm white, deep green, soft mint cards, generous spacing.
    final int BG=Color.rgb(247,249,246), SURFACE=Color.WHITE, TEXT=Color.rgb(31,42,35), MUTED=Color.rgb(104,116,107);
    final int GREEN=Color.rgb(46,125,70), GREEN_DARK=Color.rgb(31,95,51), MINT=Color.rgb(232,244,234), LINE=Color.rgb(226,232,226);
    final int ORANGE=Color.rgb(231,145,62), RED=Color.rgb(206,83,83);
    LinearLayout root, content, nav; TextView title, subtitle; SharedPreferences sp; ArrayList<Food> diary=new ArrayList<>();
    static class Food { String name, brand, meal; double kcal,p,c,f,grams; Food(String n,double k,double p,double c,double f,double g,String m){name=n;kcal=k;this.p=p;this.c=c;this.f=f;grams=g;meal=m;} }

    @Override public void onCreate(Bundle b){super.onCreate(b); sp=getSharedPreferences("nutrilab",0); loadDiary(); buildShell(); showHome();}

    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+0.5f);}
    TextView tv(String s,float size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
    GradientDrawable bg(int color,float radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    TextView pill(String text){TextView t=tv(text,12,MUTED);t.setPadding(dp(10),dp(5),dp(10),dp(5));t.setBackground(bg(Color.rgb(241,244,240),20));return t;}

    void buildShell(){
        root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setBackgroundColor(BG); setContentView(root);
        LinearLayout bar=new LinearLayout(this); bar.setGravity(Gravity.CENTER_VERTICAL); bar.setPadding(dp(20),dp(12),dp(16),dp(10)); bar.setBackgroundColor(SURFACE);
        LinearLayout brand=new LinearLayout(this); brand.setOrientation(LinearLayout.VERTICAL);
        title=tv("NutriLab",22,GREEN_DARK); title.setTypeface(null,1); brand.addView(title,new LinearLayout.LayoutParams(-1,dp(30)));
        subtitle=tv("Tu día, bajo control",12,MUTED); brand.addView(subtitle,new LinearLayout.LayoutParams(-1,dp(20)));
        bar.addView(brand,new LinearLayout.LayoutParams(0,dp(54),1));
        TextView settings=tv("⚙",22,TEXT); settings.setGravity(Gravity.CENTER); settings.setBackground(bg(Color.rgb(243,246,242),50)); settings.setOnClickListener(v->showSettings());
        bar.addView(settings,new LinearLayout.LayoutParams(dp(46),dp(46))); root.addView(bar);
        content=new LinearLayout(this); content.setOrientation(LinearLayout.VERTICAL); content.setPadding(0,dp(4),0,dp(18));
        ScrollView sv=new ScrollView(this); sv.setFillViewport(true); sv.addView(content); root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        nav=new LinearLayout(this); nav.setGravity(Gravity.CENTER); nav.setPadding(dp(4),dp(5),dp(4),dp(6)); nav.setBackgroundColor(SURFACE); root.addView(nav,new LinearLayout.LayoutParams(-1,dp(70)));
        addNav("⌂","Inicio",0); addNav("＋","Comida",1); addNav("⌕","Buscar",2); addNav("▣","Escanear",3); addNav("●","Perfil",4);
    }
    void addNav(String icon,String label,int idx){LinearLayout item=new LinearLayout(this);item.setOrientation(LinearLayout.VERTICAL);item.setGravity(Gravity.CENTER);TextView i=tv(icon,22,MUTED);i.setGravity(Gravity.CENTER);TextView l=tv(label,11,MUTED);l.setGravity(Gravity.CENTER);item.addView(i,new LinearLayout.LayoutParams(-1,dp(31)));item.addView(l,new LinearLayout.LayoutParams(-1,dp(22)));item.setOnClickListener(v->{if(idx==0)showHome();else if(idx==1)showAdd();else if(idx==2)showSearch();else if(idx==3)showScan();else showProfile();});nav.addView(item,new LinearLayout.LayoutParams(0,-1,1));}

    void clear(String h){content.removeAllViews();title.setText(h);subtitle.setText(h.equals("Hoy")?"Resumen de hoy":"NutriLab");}
    double goal(){return sp.getFloat("goal",1950);}
    double total(){double x=0;for(Food f:diary)x+=f.kcal;return x;}
    double sum(int type){double x=0;for(Food f:diary)x+=type==1?f.p:type==2?f.c:f.f;return x;}
    double mealTotal(String m){double x=0;for(Food f:diary)if(f.meal.equals(m))x+=f.kcal;return x;}

    TextView section(String s){TextView t=tv(s,18,TEXT);t.setTypeface(null,1);t.setPadding(dp(20),dp(16),dp(20),dp(8));return t;}
    LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(16),dp(14),dp(16),dp(14));l.setBackground(bg(SURFACE,18));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(14),dp(7),dp(14),dp(7));l.setLayoutParams(p);return l;}
    Button primary(String text){Button b=new Button(this);b.setText(text);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setAllCaps(false);b.setTypeface(null,1);b.setPadding(dp(12),0,dp(12),0);b.setBackground(bg(GREEN,16));return b;}
    Button outline(String text){Button b=new Button(this);b.setText(text);b.setTextColor(GREEN_DARK);b.setTextSize(14);b.setAllCaps(false);b.setBackground(bg(MINT,16));return b;}

    void showHome(){
        clear("Hoy");
        LinearLayout hero=card();
        TextView small=tv("OBJETIVO DIARIO",12,MUTED); small.setTypeface(null,1); hero.addView(small);
        LinearLayout row=new LinearLayout(this); row.setGravity(Gravity.CENTER_VERTICAL);
        LinearLayout numbers=new LinearLayout(this); numbers.setOrientation(LinearLayout.VERTICAL);
        TextView kcal=tv(String.format(Locale.US,"%.0f",total()),35,GREEN_DARK); kcal.setTypeface(null,1); numbers.addView(kcal);
        numbers.addView(tv(String.format(Locale.US,"de %.0f kcal",goal()),14,MUTED));
        row.addView(numbers,new LinearLayout.LayoutParams(0,dp(82),1));
        ProgressRing ring=new ProgressRing(this,(float)Math.min(1,total()/Math.max(1,goal()))); row.addView(ring,new LinearLayout.LayoutParams(dp(86),dp(86))); hero.addView(row);
        ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax((int)goal());pb.setProgress((int)Math.min(goal(),total()));pb.setProgressTintList(android.content.res.ColorStateList.valueOf(GREEN));pb.setBackgroundTintList(android.content.res.ColorStateList.valueOf(LINE));hero.addView(pb,new LinearLayout.LayoutParams(-1,dp(8)));
        LinearLayout macros=new LinearLayout(this);macros.setPadding(0,dp(12),0,0);macros.addView(metric("Proteínas",String.format(Locale.US,"%.0f g",sum(1))),new LinearLayout.LayoutParams(0,dp(52),1));macros.addView(metric("Carbos",String.format(Locale.US,"%.0f g",sum(2))),new LinearLayout.LayoutParams(0,dp(52),1));macros.addView(metric("Grasas",String.format(Locale.US,"%.0f g",sum(3))),new LinearLayout.LayoutParams(0,dp(52),1));hero.addView(macros);content.addView(hero);

        content.addView(section("Tus comidas")); String[] meals={"Desayuno","Almuerzo","Merienda","Cena"}; String[] icons={"☀","☼","☕","☾"};
        for(int z=0;z<meals.length;z++){String m=meals[z];LinearLayout r=card();r.setOrientation(LinearLayout.HORIZONTAL);TextView ic=tv(icons[z],23,GREEN);ic.setGravity(Gravity.CENTER);r.addView(ic,new LinearLayout.LayoutParams(dp(42),dp(54)));LinearLayout mid=new LinearLayout(this);mid.setOrientation(LinearLayout.VERTICAL);mid.setGravity(Gravity.CENTER_VERTICAL);TextView nm=tv(m,16,TEXT);nm.setTypeface(null,1);mid.addView(nm);mid.addView(tv(String.format(Locale.US,"%.0f kcal",mealTotal(m)),12,MUTED));r.addView(mid,new LinearLayout.LayoutParams(0,dp(54),1));TextView plus=tv("＋",26,GREEN);plus.setGravity(Gravity.CENTER);r.addView(plus,new LinearLayout.LayoutParams(dp(44),dp(54)));r.setOnClickListener(v->showMeal(m));content.addView(r);}

        content.addView(section("Agregar rápido"));LinearLayout quick=card();quick.setOrientation(LinearLayout.HORIZONTAL);quick.addView(quickAction("⌕","Buscar",()->showSearch()),new LinearLayout.LayoutParams(0,dp(82),1));quick.addView(quickAction("▣","Foto",()->photo()),new LinearLayout.LayoutParams(0,dp(82),1));quick.addView(quickAction("◉","Voz",()->voice()),new LinearLayout.LayoutParams(0,dp(82),1));quick.addView(quickAction("＋","Manual",()->manualDialog()),new LinearLayout.LayoutParams(0,dp(82),1));content.addView(quick);

        LinearLayout water=card();water.setOrientation(LinearLayout.HORIZONTAL);TextView wi=tv("💧",25,GREEN);water.addView(wi,new LinearLayout.LayoutParams(dp(40),dp(44)));LinearLayout wt=new LinearLayout(this);wt.setOrientation(LinearLayout.VERTICAL);wt.addView(tv("Agua",15,TEXT));wt.addView(tv(sp.getInt("water",0)+" ml hoy",12,MUTED));water.addView(wt,new LinearLayout.LayoutParams(0,dp(44),1));Button add=outline("+ 250 ml");add.setOnClickListener(v->{sp.edit().putInt("water",sp.getInt("water",0)+250).apply();showHome();});water.addView(add,new LinearLayout.LayoutParams(dp(105),dp(44)));content.addView(water);
    }
    TextView metric(String n,String v){TextView t=tv(n+"\n"+v,13,TEXT);t.setGravity(Gravity.CENTER);return t;}
    LinearLayout quickAction(String icon,String label,final Runnable r){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setGravity(Gravity.CENTER);TextView a=tv(icon,24,GREEN);a.setGravity(Gravity.CENTER);TextView b=tv(label,12,TEXT);b.setGravity(Gravity.CENTER);x.addView(a,new LinearLayout.LayoutParams(-1,dp(40)));x.addView(b,new LinearLayout.LayoutParams(-1,dp(28)));x.setOnClickListener(v->r.run());return x;}

    void showMeal(String meal){clear(meal);content.addView(section("Lo que comiste"));boolean any=false;for(Food f:new ArrayList<>(diary))if(f.meal.equals(meal)){any=true;LinearLayout r=card();r.setOrientation(LinearLayout.HORIZONTAL);LinearLayout a=new LinearLayout(this);a.setOrientation(LinearLayout.VERTICAL);a.addView(tv(f.name,16,TEXT));a.addView(tv(String.format(Locale.US,"%.0f kcal  •  %.0fg",f.kcal,f.grams),12,MUTED));r.addView(a,new LinearLayout.LayoutParams(0,dp(56),1));Button del=outline("Quitar");del.setOnClickListener(v->{diary.remove(f);saveDiary();showMeal(meal);});r.addView(del,new LinearLayout.LayoutParams(dp(90),dp(46)));content.addView(r);}if(!any){TextView e=tv("Todavía no agregaste alimentos a esta comida.",14,MUTED);e.setPadding(dp(20),dp(8),dp(20),dp(14));content.addView(e);}Button add=primary("＋  Agregar alimento");LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(50));ap.setMargins(dp(18),dp(12),dp(18),dp(12));content.addView(add,ap);add.setOnClickListener(v->showAdd());}

    void showAdd(){clear("Agregar comida");content.addView(section("¿Cómo querés registrar?"));String[] names={"Analizar una foto","Registrar por voz","Escribir y analizar con IA","Agregar manualmente","Buscar por código de barras"};String[] icons={"▣","◉","✦","＋","⌁"};Runnable[] acts={()->photo(),()->voice(),()->aiText(),()->manualDialog(),()->showScan()};for(int i=0;i<names.length;i++){LinearLayout r=card();r.setOrientation(LinearLayout.HORIZONTAL);TextView ic=tv(icons[i],25,GREEN);ic.setGravity(Gravity.CENTER);r.addView(ic,new LinearLayout.LayoutParams(dp(48),dp(56)));LinearLayout mid=new LinearLayout(this);mid.setOrientation(LinearLayout.VERTICAL);mid.addView(tv(names[i],16,TEXT));mid.addView(tv(i==0?"Detectá alimentos y cantidades":i==1?"Contá lo que comiste":i==2?"Describí tu comida":"Registrá el producto",12,MUTED));r.addView(mid,new LinearLayout.LayoutParams(0,dp(56),1));r.addView(tv("›",27,MUTED),new LinearLayout.LayoutParams(dp(32),dp(56)));final Runnable action=acts[i];r.setOnClickListener(v->action.run());content.addView(r);}}

    void manualDialog(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(8),0,dp(8),0);EditText n=field("Alimento");EditText k=field("Calorías");EditText p=field("Proteínas (g)");EditText c=field("Carbohidratos (g)");EditText f=field("Grasas (g)");EditText g=field("Cantidad (g)");l.addView(n);l.addView(k);l.addView(p);l.addView(c);l.addView(f);l.addView(g);new AlertDialog.Builder(this).setTitle("Agregar alimento").setView(l).setPositiveButton("Continuar",(d,w)->chooseMeal(new Food(n.getText().toString(),num(k),num(p),num(c),num(f),num(g),"Desayuno"))).setNegativeButton("Cancelar",null).show();}
    EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(15);e.setSingleLine(true);e.setInputType(2|8192);return e;}
    double num(EditText e){try{return Double.parseDouble(e.getText().toString());}catch(Exception x){return 0;}}
    void chooseMeal(Food f){String[] ms={"Desayuno","Almuerzo","Merienda","Cena"};new AlertDialog.Builder(this).setTitle("¿A qué comida lo agregamos?").setItems(ms,(d,w)->{f.meal=ms[w];diary.add(f);saveDiary();showHome();}).show();}

    void showSearch(){clear("Buscar alimentos");LinearLayout s=card();EditText q=field("Buscar alimento, marca o producto");q.setInputType(1);s.addView(q,new LinearLayout.LayoutParams(-1,dp(52)));Button go=primary("Buscar");s.addView(go,new LinearLayout.LayoutParams(-1,dp(48)));content.addView(s);LinearLayout tabs=new LinearLayout(this);String[] ts={"Base de datos","Favoritos","Creados"};for(String x:ts){TextView t=pill(x);t.setGravity(Gravity.CENTER);tabs.addView(t,new LinearLayout.LayoutParams(0,dp(40),1));}content.addView(tabs);LinearLayout results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);content.addView(results);go.setOnClickListener(v->{results.removeAllViews();netSearch(q.getText().toString(),results);});}

    void netSearch(String query,LinearLayout out){if(query.trim().isEmpty())return;out.addView(tv("Buscando en Open Food Facts…",14,MUTED));Executors.newSingleThreadExecutor().execute(()->{try{String u="https://world.openfoodfacts.org/api/v2/search?categories_tags=foods&countries_tags_en=argentina&search_terms="+URLEncoder.encode(query,"UTF-8")+"&page_size=15&fields=code,product_name,brands,nutriments,serving_size";String json=http(u);JSONArray arr=new JSONObject(json).optJSONArray("products");runOnUiThread(()->{out.removeAllViews();if(arr==null||arr.length()==0){out.addView(tv("No encontramos ese alimento. Probá con otra búsqueda.",15,MUTED));return;}for(int i=0;i<arr.length();i++){JSONObject p=arr.optJSONObject(i);if(p==null)continue;String name=p.optString("product_name","Producto sin nombre");String brand=p.optString("brands","");double kcal=nut(p,"energy-kcal_100g");LinearLayout r=card();r.setOrientation(LinearLayout.HORIZONTAL);TextView avatar=tv("●",22,GREEN);avatar.setGravity(Gravity.CENTER);r.addView(avatar,new LinearLayout.LayoutParams(dp(44),dp(58)));LinearLayout mid=new LinearLayout(this);mid.setOrientation(LinearLayout.VERTICAL);mid.addView(tv(name,15,TEXT));mid.addView(tv(brand+(brand.isEmpty()?"":"  •  ")+(kcal>0?String.format(Locale.US,"%.0f kcal/100g",kcal):"kcal —"),12,MUTED));r.addView(mid,new LinearLayout.LayoutParams(0,dp(58),1));r.addView(tv("›",26,MUTED),new LinearLayout.LayoutParams(dp(28),dp(58)));r.setOnClickListener(v->productDialog(p));out.addView(r);}}); }catch(Exception e){runOnUiThread(()->{out.removeAllViews();out.addView(tv("No se pudo conectar. Revisá internet.",15,RED));});}});}
    double nut(JSONObject p,String key){try{JSONObject n=p.optJSONObject("nutriments");return n==null?0:n.optDouble(key,0);}catch(Exception e){return 0;}}
    void productDialog(JSONObject p){double k=nut(p,"energy-kcal_100g"),pr=nut(p,"proteins_100g"),c=nut(p,"carbohydrates_100g"),f=nut(p,"fat_100g");String name=p.optString("product_name","Producto");LinearLayout l=card();l.addView(tv(name,21,TEXT));l.addView(tv(String.format(Locale.US,"%.0f kcal\nProteínas %.1fg   •   Carbos %.1fg   •   Grasas %.1fg\npor 100 g",k,pr,c,f),15,MUTED));new AlertDialog.Builder(this).setView(l).setPositiveButton("Agregar",(d,w)->chooseMeal(new Food(name,k,pr,c,f,100,"Desayuno"))).setNegativeButton("Cerrar",null).show();}

    void showScan(){clear("Escanear producto");content.addView(section("Código de barras"));LinearLayout c=card();c.addView(tv("Escaneá un producto o ingresá su código manualmente.",14,MUTED));EditText code=field("Ej. 7790000000000");c.addView(code,new LinearLayout.LayoutParams(-1,dp(52)));Button search=primary("Buscar producto");c.addView(search,new LinearLayout.LayoutParams(-1,dp(48)));content.addView(c);search.setOnClickListener(v->netProduct(code.getText().toString()));}
    void netProduct(String code){if(code.trim().isEmpty())return;Executors.newSingleThreadExecutor().execute(()->{try{String j=http("https://world.openfoodfacts.org/api/v2/product/"+URLEncoder.encode(code,"UTF-8")+"?fields=product_name,brands,nutriments,serving_size");JSONObject p=new JSONObject(j).optJSONObject("product");runOnUiThread(()->{if(p==null)toast("Producto no encontrado");else productDialog(p);});}catch(Exception e){runOnUiThread(()->toast("Error de conexión"));}});}

    void showProfile(){clear("Perfil");content.addView(section("Tus datos"));LinearLayout c=card();String[] labs={"Edad","Altura (cm)","Peso (kg)","Peso objetivo (kg)"};EditText[] es=new EditText[4];for(int i=0;i<4;i++){es[i]=field(labs[i]);String k=i==0?"age":i==1?"height":i==2?"weight":"target";es[i].setText(sp.getString(k,""));c.addView(es[i]);}Spinner sex=new Spinner(this);sex.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Sexo masculino","Sexo femenino"}));c.addView(sex);Spinner act=new Spinner(this);act.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Muy poca actividad","Actividad ligera","Actividad moderada","Actividad alta"}));c.addView(act);Button save=primary("Guardar y calcular objetivo");c.addView(save,new LinearLayout.LayoutParams(-1,dp(50)));content.addView(c);save.setOnClickListener(v->{for(int i=0;i<4;i++)sp.edit().putString(new String[]{"age","height","weight","target"}[i],es[i].getText().toString()).apply();double a=val(es[0]),h=val(es[1]),w=val(es[2]);int ai=act.getSelectedItemPosition();double mult=new double[]{1.2,1.375,1.55,1.725}[ai];double bmr=10*w+6.25*h-5*a+(sex.getSelectedItemPosition()==0?5:-161);double g=Math.max(1200,bmr*mult-400);sp.edit().putFloat("goal",(float)g).apply();toast("Objetivo: "+Math.round(g)+" kcal/día");showHome();});
        LinearLayout extra=card();extra.addView(tv("Peso objetivo",14,MUTED));extra.addView(tv(sp.getString("target","—")+" kg",25,GREEN_DARK));extra.addView(tv("Podemos sumar progreso, peso, actividad y gasto diario en la siguiente etapa.",12,MUTED));content.addView(extra);}
    double val(EditText e){try{return Double.parseDouble(e.getText().toString());}catch(Exception x){return 0;}}

    void showSettings(){clear("Ajustes");content.addView(section("Inteligencia artificial"));LinearLayout c=card();EditText key=field("Clave API de Gemini");key.setText(sp.getString("gemini",""));c.addView(key);Button save=primary("Guardar clave");c.addView(save,new LinearLayout.LayoutParams(-1,dp(48)));save.setOnClickListener(v->{sp.edit().putString("gemini",key.getText().toString()).apply();toast("Clave guardada en este teléfono");});content.addView(c);Button clear=outline("Borrar datos de NutriLab");content.addView(clear);clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Borrar todo").setMessage("Se eliminarán alimentos, agua y configuración local.").setPositiveButton("Borrar",(d,w)->{sp.edit().clear().apply();diary.clear();showHome();}).setNegativeButton("Cancelar",null).show());content.addView(tv("La clave de Gemini se guarda localmente en este dispositivo.",12,MUTED));}

    void aiText(){EditText e=field("Ej.: comí 2 empanadas de carne y un vaso de jugo");new AlertDialog.Builder(this).setTitle("Describe tu comida").setView(e).setPositiveButton("Analizar",(d,w)->{String key=sp.getString("gemini","");if(key.isEmpty()){toast("Primero agregá la clave de Gemini en Ajustes");return;}callGeminiText(e.getText().toString());}).setNegativeButton("Cancelar",null).show();}
    void callGeminiText(String text){toast("Analizando con Gemini…");Executors.newSingleThreadExecutor().execute(()->{try{String prompt="Analiza esta comida en español. Devuelve SOLO JSON con name, grams, kcal, protein, carbs, fat. Si faltan cantidades, estima y marca grams como estimado. Texto: "+text;String out=gemini(prompt,null);runOnUiThread(()->showAiResult(out));}catch(Exception e){runOnUiThread(()->toast("No se pudo analizar con Gemini: "+e.getMessage()));}});}
    String gemini(String prompt,String imageB64)throws Exception{String key=sp.getString("gemini","");if(key.isEmpty())throw new Exception("falta API key");String url="https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key="+URLEncoder.encode(key,"UTF-8");JSONObject body=new JSONObject();JSONArray parts=new JSONArray();JSONObject tp=new JSONObject();tp.put("text",prompt);parts.put(tp);if(imageB64!=null){JSONObject ip=new JSONObject();JSONObject inline=new JSONObject();inline.put("mime_type","image/jpeg");inline.put("data",imageB64);ip.put("inline_data",inline);parts.put(ip);}JSONArray contents=new JSONArray();JSONObject cc=new JSONObject();cc.put("parts",parts);contents.put(cc);body.put("contents",contents);return postJson(url,body.toString());}
    String postJson(String u,String body)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(30000);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder sb=new StringBuilder();String l;while((l=br.readLine())!=null)sb.append(l);c.disconnect();if(code<200||code>=300)throw new Exception("HTTP "+code);return sb.toString();}
    void showAiResult(String raw){try{JSONObject j=new JSONObject(raw);String text=j.getJSONArray("candidates").getJSONObject(0).getJSONObject("content").getJSONArray("parts").getJSONObject(0).optString("text","");text=text.replace("```json","").replace("```","").trim();JSONObject o=new JSONObject(text);String name=o.optString("name","Comida analizada");double k=o.optDouble("kcal",0),p=o.optDouble("protein",0),c=o.optDouble("carbs",0),f=o.optDouble("fat",0),g=o.optDouble("grams",0);new AlertDialog.Builder(this).setTitle("Confirma tus alimentos").setMessage(String.format(Locale.US,"%s\n\n%.0f kcal\nProteínas %.1fg  •  Carbos %.1fg  •  Grasas %.1fg\nCantidad: %.0fg",name,k,p,c,f,g)).setPositiveButton("Agregar",(d,w)->chooseMeal(new Food(name,k,p,c,f,g,"Desayuno"))).setNegativeButton("Cancelar",null).show();}catch(Exception e){new AlertDialog.Builder(this).setTitle("Resultado de IA").setMessage(raw).setPositiveButton("Cerrar",null).show();}}

    void voice(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission("android.permission.RECORD_AUDIO")!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{"android.permission.RECORD_AUDIO"},55);return;}Intent i=new Intent("android.speech.action.RECOGNIZE_SPEECH");i.putExtra("android.speech.extra.LANGUAGE_MODEL","free_form");i.putExtra("android.speech.extra.LANGUAGE","es-AR");try{startActivityForResult(i,77);}catch(Exception e){toast("El reconocimiento de voz no está disponible");}}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==88&&c==RESULT_OK&&d!=null&&d.getData()!=null){analyzeImage(d.getData());return;}if(r==77&&c==RESULT_OK&&d!=null){ArrayList<String>a=d.getStringArrayListExtra("android.speech.extra.RESULTS");if(a!=null&&!a.isEmpty()){new AlertDialog.Builder(this).setTitle("Confirma tus alimentos").setMessage(a.get(0)).setPositiveButton("Continuar",(x,w)->aiTextFrom(a.get(0))).setNegativeButton("Cancelar",null).show();}}}
    void aiTextFrom(String s){String key=sp.getString("gemini","");if(key.isEmpty()){toast("Agregá la clave de Gemini en Ajustes");return;}callGeminiText(s);}
    void photo(){Intent i=new Intent(Intent.ACTION_PICK);i.setType("image/*");try{startActivityForResult(i,88);}catch(Exception e){toast("No se pudo abrir la galería");}}
    void analyzeImage(Uri uri){try{InputStream in=getContentResolver().openInputStream(uri);Bitmap b=BitmapFactory.decodeStream(in);ByteArrayOutputStream out=new ByteArrayOutputStream();b.compress(Bitmap.CompressFormat.JPEG,75,out);String b64=android.util.Base64.encodeToString(out.toByteArray(),android.util.Base64.NO_WRAP);toast("Analizando foto con Gemini…");Executors.newSingleThreadExecutor().execute(()->{try{String prompt="Analiza esta foto de comida. Identifica los alimentos visibles y estima cantidades. Devuelve SOLO JSON con name, grams, kcal, protein, carbs, fat para el plato completo. No inventes marcas.";String raw=gemini(prompt,b64);runOnUiThread(()->showAiResult(raw));}catch(Exception e){runOnUiThread(()->toast("No se pudo analizar la foto: "+e.getMessage()));}});}catch(Exception e){toast("No se pudo leer la imagen");}}
    String http(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setRequestProperty("User-Agent","NutriLab/2.0 (Android local prototype)");try(InputStream in=c.getInputStream();BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){StringBuilder s=new StringBuilder();String l;while((l=br.readLine())!=null)s.append(l);return s.toString();}finally{c.disconnect();}}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    void saveDiary(){JSONArray a=new JSONArray();try{for(Food f:diary){JSONObject o=new JSONObject();o.put("n",f.name);o.put("k",f.kcal);o.put("p",f.p);o.put("c",f.c);o.put("f",f.f);o.put("g",f.grams);o.put("m",f.meal);a.put(o);}sp.edit().putString("diary",a.toString()).apply();}catch(Exception ignored){}}
    void loadDiary(){try{JSONArray a=new JSONArray(sp.getString("diary","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);diary.add(new Food(o.optString("n"),o.optDouble("k"),o.optDouble("p"),o.optDouble("c"),o.optDouble("f"),o.optDouble("g"),o.optString("m","Desayuno")));}}catch(Exception ignored){}}

    static class ProgressRing extends View {Paint p=new Paint(1);float value;public ProgressRing(Context c,float v){super(c);value=v;p.setStrokeWidth(10);p.setStyle(Paint.Style.STROKE);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}protected void onDraw(Canvas c){super.onDraw(c);float cx=getWidth()/2f,cy=getHeight()/2f,r=Math.min(cx,cy)-8;p.setColor(Color.rgb(230,236,230));p.setStrokeCap(Paint.Cap.ROUND);c.drawCircle(cx,cy,r,p);p.setColor(Color.rgb(46,125,70));RectF q=new RectF(cx-r,cy-r,cx+r,cy+r);c.drawArc(q,-90,360*value,false,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(31,95,51));p.setTextAlign(Paint.Align.CENTER);p.setTextSize(18);p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText(Math.round(value*100)+"%",cx,cy+6,p);p.setStyle(Paint.Style.STROKE);}}
}
