package com.nutrilab.app;

import android.app.*;
import android.os.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.util.Base64;
import android.net.Uri;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.Executors;
import org.json.*;

public class MainActivity extends Activity {
    LinearLayout root, content; SharedPreferences sp; TextView title, kcalText; final int GREEN=Color.rgb(46,125,50); final int GRAY=Color.rgb(95,99,104);
    int blue=Color.rgb(25,118,210); ArrayList<Food> diary=new ArrayList<>();
    static class Food { String name, brand, meal; double kcal,p,c,f,grams; Food(String n,double k,double p,double c,double f,double g,String m){name=n;kcal=k;this.p=p;this.c=c;this.f=f;grams=g;meal=m;} }
    @Override public void onCreate(Bundle b){super.onCreate(b); sp=getSharedPreferences("nutrilab",0); loadDiary(); build(); showHome();}
    void build(){
        root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setBackgroundColor(Color.rgb(248,250,248)); setContentView(root);
        LinearLayout top=new LinearLayout(this); top.setGravity(Gravity.CENTER_VERTICAL); top.setPadding(22,16,22,12); top.setBackgroundColor(Color.WHITE);
        title=tv("NutriLab",22,Color.DKGRAY); top.addView(title,new LinearLayout.LayoutParams(0,60,1));
        TextView gear=tv("⚙",26,GRAY); gear.setGravity(Gravity.CENTER); gear.setOnClickListener(v->showSettings()); top.addView(gear,new LinearLayout.LayoutParams(56,60)); root.addView(top);
        content=new LinearLayout(this); content.setOrientation(LinearLayout.VERTICAL); ScrollView sv=new ScrollView(this); sv.addView(content); root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout nav=new LinearLayout(this); nav.setGravity(Gravity.CENTER); nav.setBackgroundColor(Color.WHITE); String[] ns={"Inicio","Comida","Buscar","Escanear","Perfil"};
        for(String n:ns){TextView x=tv(n,12,GRAY);x.setGravity(Gravity.CENTER);x.setOnClickListener(v->{switch(n){case"Inicio":showHome();break;case"Comida":showAdd();break;case"Buscar":showSearch();break;case"Escanear":showScan();break;case"Perfil":showProfile();}});nav.addView(x,new LinearLayout.LayoutParams(0,64,1));} root.addView(nav);
    }
    TextView tv(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(12,8,12,8);return t;}
    Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
    TextView head(String s){TextView t=tv(s,19,Color.DKGRAY);t.setTypeface(null,1);t.setPadding(18,18,18,8);return t;}
    void clear(String h){content.removeAllViews();title.setText(h);}
    double goal(){return sp.getFloat("goal",1950);}
    double total(){double x=0;for(Food f:diary)x+=f.kcal;return x;}
    void showHome(){clear("Hoy");
        LinearLayout card=card(); TextView a=tv("Calorías",15,GRAY); card.addView(a); kcalText=tv(String.format(Locale.US,"%.0f / %.0f kcal",total(),goal()),30,GREEN);card.addView(kcalText); ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax((int)goal());pb.setProgress((int)Math.min(goal(),total()));card.addView(pb,new LinearLayout.LayoutParams(-1,18));
        LinearLayout macros=new LinearLayout(this);macros.addView(metric("Proteínas",sum(1)+" g"));macros.addView(metric("Carbos",sum(2)+" g"));macros.addView(metric("Grasas",sum(3)+" g"));card.addView(macros);content.addView(card);
        content.addView(head("Tus comidas"));String[] meals={"Desayuno","Almuerzo","Merienda","Cena"};for(String m:meals){LinearLayout r=card();r.addView(tv(m,17,Color.DKGRAY),new LinearLayout.LayoutParams(0,60,1));r.addView(tv(String.format(Locale.US,"%.0f kcal",mealTotal(m)),15,GRAY));r.setOnClickListener(v->showMeal(m));content.addView(r);}
        content.addView(head("Acciones rápidas"));LinearLayout q=card();q.addView(action("📷\nFoto"));q.addView(action("🎙\nVoz"));q.addView(action("✏️\nManual"));q.addView(action("▦\nCódigo"));content.addView(q);Button water=btn("💧 Agua  •  "+sp.getInt("water",0)+" ml");water.setOnClickListener(v->{sp.edit().putInt("water",sp.getInt("water",0)+250).apply();showHome();});content.addView(water);
    }
    TextView metric(String n,String v){TextView t=tv(n+"\n"+v,13,GRAY);t.setGravity(Gravity.CENTER);return t;}
    TextView action(String s){TextView t=tv(s,14,GREEN);t.setGravity(Gravity.CENTER);t.setOnClickListener(v->{if(s.contains("Foto"))photo();else if(s.contains("Voz"))voice();else if(s.contains("Código"))showScan();else showAdd();});return t;}
    LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(18,14,18,14);l.setBackgroundColor(Color.WHITE);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(12,8,12,8);l.setLayoutParams(p);return l;}
    double sum(int type){double x=0;for(Food f:diary)x+=type==1?f.p:type==2?f.c:f.f;return x;}
    double mealTotal(String m){double x=0;for(Food f:diary)if(f.meal.equals(m))x+=f.kcal;return x;}
    void showMeal(String meal){clear(meal);for(Food f:new ArrayList<>(diary))if(f.meal.equals(meal)){LinearLayout r=card();r.addView(tv(f.name+"\n"+String.format(Locale.US,"%.0f kcal • %.0fg",f.kcal,f.grams),16,Color.DKGRAY),new LinearLayout.LayoutParams(0,70,1));Button del=btn("Eliminar");del.setOnClickListener(v->{diary.remove(f);saveDiary();showMeal(meal);});r.addView(del);content.addView(r);}Button add=btn("+ Agregar alimento");add.setOnClickListener(v->showAdd());content.addView(add);}
    void showAdd(){clear("Agregar comida");content.addView(head("¿Qué comiste?"));Button photo=btn("📷 Analizar una foto");photo.setOnClickListener(v->photo());content.addView(photo);Button voice=btn("🎙 Registrar por voz");voice.setOnClickListener(v->voice());content.addView(voice);Button text=btn("🤖 Escribir y analizar con IA");text.setOnClickListener(v->aiText());content.addView(text);Button manual=btn("✏️ Agregar manualmente");manual.setOnClickListener(v->manualDialog());content.addView(manual);Button barcode=btn("▦ Buscar por código de barras");barcode.setOnClickListener(v->showScan());content.addView(barcode);}
    void manualDialog(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(30,10,30,10);EditText n=field("Alimento");EditText k=field("Calorías");EditText p=field("Proteínas (g)");EditText c=field("Carbohidratos (g)");EditText f=field("Grasas (g)");EditText g=field("Cantidad (g)");l.addView(n);l.addView(k);l.addView(p);l.addView(c);l.addView(f);l.addView(g);new AlertDialog.Builder(this).setTitle("Agregar alimento").setView(l).setPositiveButton("Continuar",(d,w)->chooseMeal(new Food(n.getText().toString(),num(k),num(p),num(c),num(f),num(g),"Desayuno"))).setNegativeButton("Cancelar",null).show();}
    EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setInputType(2|8192);return e;} double num(EditText e){try{return Double.parseDouble(e.getText().toString());}catch(Exception x){return 0;}}
    void chooseMeal(Food f){String[] ms={"Desayuno","Almuerzo","Merienda","Cena"};new AlertDialog.Builder(this).setTitle("¿A qué comida lo agregamos?").setItems(ms,(d,w)->{f.meal=ms[w];diary.add(f);saveDiary();showHome();}).show();}
    void showSearch(){clear("Buscar alimentos");EditText q=field("Buscar alimentos");content.addView(q);Button go=btn("Buscar en Open Food Facts");content.addView(go);LinearLayout results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);content.addView(results);go.setOnClickListener(v->{results.removeAllViews();netSearch(q.getText().toString(),results);});}
    void netSearch(String query,LinearLayout out){if(query.trim().isEmpty())return;out.addView(tv("Buscando…",14,GRAY));Executors.newSingleThreadExecutor().execute(()->{try{String u="https://world.openfoodfacts.org/api/v2/search?categories_tags=foods&countries_tags_en=argentina&search_terms="+URLEncoder.encode(query,"UTF-8")+"&page_size=15&fields=code,product_name,brands,nutriments,serving_size";String json=http(u);JSONArray arr=new JSONObject(json).optJSONArray("products");runOnUiThread(()->{out.removeAllViews();if(arr==null||arr.length()==0){out.addView(tv("No se encontraron resultados.",15,GRAY));return;}for(int i=0;i<arr.length();i++){JSONObject p=arr.optJSONObject(i);if(p==null)continue;String name=p.optString("product_name","Producto sin nombre");String brand=p.optString("brands","");double kcal=nut(p,"energy-kcal_100g");LinearLayout r=card();r.addView(tv(name+"\n"+brand+" • "+(kcal>0?String.format(Locale.US,"%.0f kcal/100g",kcal):"kcal —"),16,Color.DKGRAY));r.setOnClickListener(v->productDialog(p));out.addView(r);}}); }catch(Exception e){runOnUiThread(()->{out.removeAllViews();out.addView(tv("No se pudo conectar. Revisá internet.",15,Color.RED));});}});}
    double nut(JSONObject p,String key){try{return p.optJSONObject("nutriments").optDouble(key,0);}catch(Exception e){return 0;}}
    void productDialog(JSONObject p){double k=nut(p,"energy-kcal_100g"),pr=nut(p,"proteins_100g"),c=nut(p,"carbohydrates_100g"),f=nut(p,"fat_100g");String name=p.optString("product_name","Producto");LinearLayout l=card();l.addView(tv(name,21,Color.DKGRAY));l.addView(tv(String.format(Locale.US,"%.0f kcal\nP %.1fg   C %.1fg   G %.1fg\npor 100 g",k,pr,c,f),17,GRAY));Button add=btn("Agregar a comida");l.addView(add);new AlertDialog.Builder(this).setView(l).setPositiveButton("Agregar",(d,w)->chooseMeal(new Food(name,k,pr,c,f,100,"Desayuno"))).setNegativeButton("Cerrar",null).show();}
    void showScan(){clear("Escanear");content.addView(tv("Escáner de código de barras",20,Color.DKGRAY));content.addView(tv("Esta V1 usa ingreso manual como respaldo universal. Luego podemos conectar cámara/ML Kit sin cambiar el flujo.",15,GRAY));EditText code=field("Código de barras");content.addView(code);Button search=btn("Buscar producto");content.addView(search);search.setOnClickListener(v->netProduct(code.getText().toString()));}
    void netProduct(String code){if(code.trim().isEmpty())return;new AlertDialog.Builder(this).setMessage("Buscando producto…").show();Executors.newSingleThreadExecutor().execute(()->{try{String j=http("https://world.openfoodfacts.org/api/v2/product/"+URLEncoder.encode(code,"UTF-8")+"?fields=product_name,brands,nutriments,serving_size");JSONObject p=new JSONObject(j).optJSONObject("product");runOnUiThread(()->{if(p==null)toast("Producto no encontrado");else productDialog(p);});}catch(Exception e){runOnUiThread(()->toast("Error de conexión"));}});}
    void showProfile(){clear("Perfil");String[] labs={"Edad","Altura (cm)","Peso (kg)","Peso objetivo (kg)"};for(String key:labs){EditText e=field(key);String k=key.equals("Edad")?"age":key.startsWith("Altura")?"height":key.startsWith("Peso objetivo")?"target":"weight";e.setText(sp.getString(k,""));content.addView(e);}Spinner sex=new Spinner(this);sex.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Sexo masculino","Sexo femenino"}));content.addView(sex);Spinner act=new Spinner(this);act.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Muy poca","Ligera","Moderada","Alta"}));content.addView(act);Button save=btn("Guardar y calcular objetivo");content.addView(save);save.setOnClickListener(v->{EditText[] es=new EditText[4];for(int i=0;i<4;i++)es[i]=(EditText)content.getChildAt(i+1);for(int i=0;i<4;i++)sp.edit().putString(new String[]{"age","height","weight","target"}[i],es[i].getText().toString()).apply();double a=val(es[0]),h=val(es[1]),w=val(es[2]);int ai=act.getSelectedItemPosition();double mult=new double[]{1.2,1.375,1.55,1.725}[ai];double bmr=10*w+6.25*h-5*a+(sex.getSelectedItemPosition()==0?5:-161);double g=Math.max(1200,bmr*mult-400);sp.edit().putFloat("goal",(float)g).apply();toast("Objetivo calculado: "+Math.round(g)+" kcal");showHome();});}
    double val(EditText e){try{return Double.parseDouble(e.getText().toString());}catch(Exception x){return 0;}}
    void showSettings(){clear("Ajustes");content.addView(head("Inteligencia artificial"));EditText key=field("Clave API de Gemini");key.setText(sp.getString("gemini", ""));content.addView(key);Button save=btn("Guardar clave");save.setOnClickListener(v->{sp.edit().putString("gemini",key.getText().toString()).apply();toast("Guardado en este teléfono");});content.addView(save);Button clear=btn("Borrar datos de NutriLab");clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Borrar todo").setMessage("Se eliminarán alimentos, agua y configuración local.").setPositiveButton("Borrar",(d,w)->{sp.edit().clear().apply();diary.clear();showHome();}).setNegativeButton("Cancelar",null).show());content.addView(clear);content.addView(tv("La clave de Gemini se guarda localmente en este dispositivo. No la compartas.",13,GRAY));}
    void aiText(){EditText e=field("Ej.: comí 2 empanadas de carne y un vaso de jugo");new AlertDialog.Builder(this).setTitle("Describe tu comida").setView(e).setPositiveButton("Analizar",(d,w)->{String key=sp.getString("gemini","");if(key.isEmpty()){toast("Primero agregá la clave de Gemini en Ajustes");return;} callGeminiText(e.getText().toString());}).setNegativeButton("Cancelar",null).show();}
    void callGeminiText(String text){toast("Analizando con Gemini…");Executors.newSingleThreadExecutor().execute(()->{try{String prompt="Analiza esta comida en español. Devuelve SOLO JSON con name, grams, kcal, protein, carbs, fat. Si faltan cantidades, estima y marca grams como estimado. Texto: "+text;String out=gemini(prompt,null);runOnUiThread(()->showAiResult(out));}catch(Exception e){runOnUiThread(()->toast("No se pudo analizar con Gemini: "+e.getMessage()));}});}
    String gemini(String prompt,String imageB64)throws Exception{String key=sp.getString("gemini","");if(key.isEmpty())throw new Exception("falta API key");String url="https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key="+URLEncoder.encode(key,"UTF-8");JSONObject body=new JSONObject();JSONArray parts=new JSONArray();JSONObject tp=new JSONObject();tp.put("text",prompt);parts.put(tp);if(imageB64!=null){JSONObject ip=new JSONObject();JSONObject inline=new JSONObject();inline.put("mime_type","image/jpeg");inline.put("data",imageB64);ip.put("inline_data",inline);parts.put(ip);}JSONArray contents=new JSONArray();JSONObject c=new JSONObject();c.put("parts",parts);contents.put(c);body.put("contents",contents);return postJson(url,body.toString());}
    String postJson(String u,String body)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(30000);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder sb=new StringBuilder();String l;while((l=br.readLine())!=null)sb.append(l);c.disconnect();if(code<200||code>=300)throw new Exception("HTTP "+code);return sb.toString();}
    void showAiResult(String raw){try{JSONObject j=new JSONObject(raw);String text=j.getJSONArray("candidates").getJSONObject(0).getJSONObject("content").getJSONArray("parts").getJSONObject(0).optString("text","");text=text.replace("```json","").replace("```","").trim();JSONObject o=new JSONObject(text);String name=o.optString("name","Comida analizada");double k=o.optDouble("kcal",0),p=o.optDouble("protein",0),c=o.optDouble("carbs",0),f=o.optDouble("fat",0),g=o.optDouble("grams",0);new AlertDialog.Builder(this).setTitle("Confirma tus alimentos").setMessage(String.format(Locale.US,"%s\n\n%.0f kcal\nProteínas %.1fg  •  Carbos %.1fg  •  Grasas %.1fg\nCantidad: %.0fg",name,k,p,c,f,g)).setPositiveButton("Agregar",(d,w)->chooseMeal(new Food(name,k,p,c,f,g,"Desayuno"))).setNegativeButton("Cancelar",null).show();}catch(Exception e){new AlertDialog.Builder(this).setTitle("Resultado de IA").setMessage(raw).setPositiveButton("Cerrar",null).show();}}
    void voice(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission("android.permission.RECORD_AUDIO")!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{"android.permission.RECORD_AUDIO"},55);return;}Intent i=new Intent("android.speech.action.RECOGNIZE_SPEECH");i.putExtra("android.speech.extra.LANGUAGE_MODEL","free_form");i.putExtra("android.speech.extra.LANGUAGE","es-AR");try{startActivityForResult(i,77);}catch(Exception e){toast("El reconocimiento de voz no está disponible");}}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==88&&c==RESULT_OK&&d!=null&&d.getData()!=null){analyzeImage(d.getData());return;}if(r==77&&c==RESULT_OK&&d!=null){ArrayList<String>a=d.getStringArrayListExtra("android.speech.extra.RESULTS");if(a!=null&&!a.isEmpty()){new AlertDialog.Builder(this).setTitle("Confirma tus alimentos").setMessage(a.get(0)).setPositiveButton("Continuar",(x,w)->aiTextFrom(a.get(0))).setNegativeButton("Cancelar",null).show();}}}
    void aiTextFrom(String s){toast("Texto recibido: "+s+". Falta enviar al modelo configurado.");}
    void photo(){Intent i=new Intent(Intent.ACTION_PICK);i.setType("image/*");try{startActivityForResult(i,88);}catch(Exception e){toast("No se pudo abrir la galería");}}
    void analyzeImage(Uri uri){try{InputStream in=getContentResolver().openInputStream(uri);Bitmap b=BitmapFactory.decodeStream(in);ByteArrayOutputStream out=new ByteArrayOutputStream();b.compress(Bitmap.CompressFormat.JPEG,75,out);String b64=Base64.encodeToString(out.toByteArray(),Base64.NO_WRAP);toast("Analizando foto con Gemini…");Executors.newSingleThreadExecutor().execute(()->{try{String prompt="Analiza esta foto de comida. Identifica los alimentos visibles y estima cantidades. Devuelve SOLO JSON con name, grams, kcal, protein, carbs, fat para el plato completo. No inventes marcas.";String raw=gemini(prompt,b64);runOnUiThread(()->showAiResult(raw));}catch(Exception e){runOnUiThread(()->toast("No se pudo analizar la foto: "+e.getMessage()));}});}catch(Exception e){toast("No se pudo leer la imagen");}}
    String http(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setRequestProperty("User-Agent","NutriLab/1.0 (Android local prototype)");try(InputStream in=c.getInputStream();BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){StringBuilder s=new StringBuilder();String l;while((l=br.readLine())!=null)s.append(l);return s.toString();}finally{c.disconnect();}}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    void saveDiary(){JSONArray a=new JSONArray();try{for(Food f:diary){JSONObject o=new JSONObject();o.put("n",f.name);o.put("k",f.kcal);o.put("p",f.p);o.put("c",f.c);o.put("f",f.f);o.put("g",f.grams);o.put("m",f.meal);a.put(o);}sp.edit().putString("diary",a.toString()).apply();}catch(Exception ignored){}}
    void loadDiary(){try{JSONArray a=new JSONArray(sp.getString("diary","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);diary.add(new Food(o.optString("n"),o.optDouble("k"),o.optDouble("p"),o.optDouble("c"),o.optDouble("f"),o.optDouble("g"),o.optString("m","Desayuno")));}}catch(Exception ignored){}}
}
